namespace MCELoader.Shared.ProxyTypes;

#if MCEEditor
public enum EquipmentID
{
    None = -1,
    Bat = 0,
    Pipe = 1,
    Crowbar = 2,
    Machete = 3,
    RiotStick = 4,
    Katana = 5,
    BrokenKatana = 6,
    Axe = 7,
    Laser_Melee = 8,
    Blaster = 34,
    SMG = 35,
    Revolver = 36,
    Shotgun = 37,
    Kalashnikov = 38,
    RubberGun = 39,
    PlasmaPistol = 40,
    RebarGun = 41,
    Minigun = 42,
    Revolver_Golden = 43,
    Chain = 66,
    TrafficSign = 67,
    Chainsaw = 68,
    Sledgehammer = 69,
    Laser_Ranged = 70,
    ConfettiGun = 71,
    Molotov = 100,
    CherryBomb = 101,
    FragGrenade = 102,
    Shuriken = 103,
    Brick = 104,
    Flashbang = 105,
    Caltrops = 106,
    EMPgrenade = 107,
    Jerrycan = 108,
    FoamBomb = 109,
    RiotShield = 120,
    BODY_ARMOR_DUMMY = 127,
}
#endif
